# Generated by Django 4.2.26 on 2025-11-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_due_date_alter_task_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('title', 'due_date'), name='unique_task_title_due'),
        ),
    ]
