# Generated by Django 4.2.26 on 2025-11-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_due_date_alter_task_estimated_hours_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_title_due',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(default=5, help_text='1-10 Scale'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
